version: "3.8"

services:
  rabbitmq_server:
    image: mrsal
    build:
      context: .
    container_name: mrsal
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    ports:
      # RabbitMQ container listening on the default port of 5672.
      # Expose default port to the port 5673
      - "${RABBITMQ_CONTAINER_PORT}:5672"
      # OPTIONAL: Expose the GUI port
      - "${RABBITMQ_GUI_PORT}:15672"
