version: "3.9"

services:
  rabbitmq_server:
    image: mrsal-v0.7.1
    build:
      context: .
    container_name: mrsal
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    ports:
      # RabbitMQ container listening on the default port of 5672.
      - "5672:5672"
      - "5671:5671"
      # OPTIONAL: Expose the GUI port
      - "${RABBITMQ_GUI_PORT}:15672"
    volumes:
      - ${BASE_PATH}/storage/rabbitmq:/etc/rabbitmq/certs
      - ${BASE_PATH}/storage/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - gateway

# Make the externally created network "gateway" available as network "default" 
# If "gateway" not exists then create it with
# docker network create --internal=false --attachable --driver=bridge gateway
networks:
  gateway:
    external: true

# If you want to let the docker compose create the network, then use:
# networks:
#   gateway:
#     name: gateway